# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY

_commit: ab1cffa
_src_path: https://github.com/mantoso/terraform-module-template
aws: false
aws_provider_version: '>= 4.0.0, < 5.0.0'
company_name: Mantoso
conduct_email: conduct@mantoso.com
copyright_holder: Mantoso Corporation
copyright_license: Apache License 2.0
copyright_year: '2023'
gitlab_url: https://gitlab.mantoso.com
initial_codeowners: '@tracphil'
module_name: GitHub Repository
security_email: security@mantoso.com
terraform_version: '>= 1.3.7'

